### PR TITLE
Add reset model function

### PR DESCRIPTION
**Pull request by miloit**
Add reset model function

### CODE REVIEW

**Comment by zehnm** [comment]
@miloit is this ready for review?
After a PR is opened, there shouldn't be more changes, unless requested.
Otherwise please use the "draft pull request" if it's not finished yet and to get an initial feedback.

**Comment by miloit** [comment]
@zehnm yes it is. Sorry I faster than you 😉 will consider it the next time.

**Review by zehnm — APPROVED** [review]
Looks good.
This is a breaking change and will require to update all integration plugins. I'll release the library as new major version 1.0.0 after I add the additional metadata for the new plugin loading checks.
@martonborzak could you quickly check if there are no additional side effects with renaming `F_TVCHANNELLIST` --> `F_MEDIAPLAYERCHANNELLIST`? As far as I see this is only used in milo's Kodi plugin so far.

**Comment by martonborzak** [comment]
The renaming can work as long as it's also renamed in `remote-software`

**Pull request merged**
